{{- if .Values.collector.enabled -}}
apiVersion: v1
{{ if .Values.collector.useSecret -}}
kind: Secret
{{- else -}}
kind: ConfigMap
{{- end }}
metadata:
  labels:
    app.kubernetes.io/name : {{ template "wavefront.fullname" . }}
    helm.sh/chart: {{ template "wavefront.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io.instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: collector
  name: {{ template "wavefront.collector.fullname" . }}-config
data:
  config.yaml: |
{{ if .Values.collector.useSecret -}}
{{ include "config.data" . | b64enc | indent 4 -}}
{{- else -}}
{{ include "config.data" . | indent 4 }}
{{- end }}
{{ end }}
